service: serverless-ecommerce

package:
  individually: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'local'}
  region: us-east-1
  environment:
    IS_LOCAL: ${opt:stage, 'dev'}
  versionFunctions: false

plugins:
  - serverless-localstack
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'npm'
    includeModules: true
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: hello
  goodbye:
    handler: src/handler2.goodbye
    events:
      - http:
          method: get
          path: goodbye
